import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.185.1/build/three.module.js';
import {BlockRegistry} from './blocks.js';import {ModManager} from './mods.js';import {World} from './world.js';import {Input} from './input.js';import {Player} from './player.js';import {MobManager} from './mobs.js';import {Particles} from './particles.js';import {UI} from './ui.js';

const registry=new BlockRegistry(),mods=new ModManager(registry),ui=new UI(registry,mods);ui.refreshHotbar();
const scene=new THREE.Scene();scene.background=new THREE.Color(0x7db9dd);scene.fog=new THREE.Fog(0x7db9dd,22,78);
const camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.05,120);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=false;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;document.getElementById('game').append(renderer.domElement);
const hemi=new THREE.HemisphereLight(0xbfe4ff,0x24301f,1.25);scene.add(hemi);const sun=new THREE.DirectionalLight(0xfff2cf,2.15);sun.position.set(25,40,12);scene.add(sun);
const starsGeo=new THREE.BufferGeometry(),sp=[];for(let i=0;i<500;i++){const r=85,a=Math.random()*Math.PI*2,b=Math.acos(THREE.MathUtils.randFloat(.05,.95));sp.push(Math.sin(b)*Math.cos(a)*r,Math.cos(b)*r,Math.sin(b)*Math.sin(a)*r)}starsGeo.setAttribute('position',new THREE.Float32BufferAttribute(sp,3));const stars=new THREE.Points(starsGeo,new THREE.PointsMaterial({color:0xffffff,size:.18,sizeAttenuation:true,transparent:true,opacity:0}));scene.add(stars);
let save=null;try{save=JSON.parse(localStorage.getItem('voxelforge_save')||'null')}catch{}
const seed=save?.seed??Math.floor(Math.random()*1e9),world=new World(scene,registry,seed);world.generate(save?.edits);
const input=new Input(renderer.domElement,ui),player=new Player(camera,world,input,mods);if(save?.player)player.load(save.player);else player.respawn();const mobs=new MobManager(scene,world,player),particles=new Particles(scene);const raycaster=new THREE.Raycaster();raycaster.far=5.25;
let running=false,last=performance.now(),worldTime=save?.worldTime??.25,breakTarget='',breakProgress=0,lastSave=0;

function saveGame(){const payload={version:1,seed,worldTime,player:player.save(),edits:world.serializeEdits()};try{localStorage.setItem('voxelforge_save',JSON.stringify(payload))}catch{}}
function aimHit(){raycaster.setFromCamera(new THREE.Vector2(0,0),camera);const mobHit=mobs.raycast(raycaster);const blockHits=raycaster.intersectObjects(world.meshes,false);const b=blockHits.find(h=>h.distance<=5.2);if(mobHit&&(!b||mobHit.hit.distance<b.distance))return {type:'mob',...mobHit};if(!b)return null;const n=b.face.normal.clone().transformDirection(b.object.matrixWorld).round();const inside=b.point.clone().addScaledVector(n,-.01),outside=b.point.clone().addScaledVector(n,.01);return {type:'block',hit:b,normal:n,inside:new THREE.Vector3(Math.floor(inside.x),Math.floor(inside.y),Math.floor(inside.z)),outside:new THREE.Vector3(Math.floor(outside.x),Math.floor(outside.y),Math.floor(outside.z))}}
function updateActions(dt){
  const target=aimHit();if(input.breakHeld&&target){if(target.type==='mob'){const key='mob-'+mobs.mobs.indexOf(target.mob);if(key!==breakTarget){breakTarget=key;breakProgress=0}breakProgress+=dt*3.3;if(breakProgress>=1){mobs.hit(target.mob);breakProgress=0;ui.toast('Hit mob')}}else{const p=target.inside,key=`${p.x},${p.y},${p.z}`;if(key!==breakTarget){breakTarget=key;breakProgress=0}const id=world.get(p.x,p.y,p.z),b=registry.get(id);breakProgress+=dt*mods.effect('breakSpeed',1)/Math.max(.15,b.hardness*.42);if(breakProgress>=1){const removed=world.breakAt(p.x,p.y,p.z);if(removed){particles.burst(p,new THREE.Color(registry.get(removed).color),12);ui.toast(`Broke ${registry.get(removed).name}`)}breakProgress=0}}}else{breakTarget='';breakProgress=Math.max(0,breakProgress-dt*4)}ui.breakProgress(Math.min(1,breakProgress));
  if(input.consumePlace()&&target?.type==='block'){const p=target.outside,id=ui.selectedBlock();if(!player.intersectsBlock(p.x,p.y,p.z)&&world.placeAt(p.x,p.y,p.z,id)){particles.burst(p,new THREE.Color(registry.get(id).color),5);ui.toast(`Placed ${registry.get(id).name}`)}}
}
function updateSky(dt){worldTime=(worldTime+dt/180)%1;const angle=worldTime*Math.PI*2-Math.PI/2,day=Math.max(0,Math.sin(angle)*.5+.5),sunHeight=Math.sin(angle),sky=new THREE.Color().setHSL(.57,.5,.08+day*.56);scene.background.copy(sky);scene.fog.color.copy(sky);sun.position.set(Math.cos(angle)*45,Math.sin(angle)*58,18);sun.intensity=.15+day*2.5;hemi.intensity=(.18+day*1.1)*(mods.flag('nightVision')?2.3:1);stars.material.opacity=Math.max(0,(.32-day)*2.8);const total=worldTime*24,h=Math.floor(total),m=Math.floor((total-h)*60);ui.statusPill.textContent=`DAY ${Math.floor((save?.days||0)+1)} · ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`}
function loop(now){requestAnimationFrame(loop);const dt=Math.min(.045,(now-last)/1000);last=now;if(!running)return;player.update(dt);updateActions(dt);mobs.update(dt,now/1000);particles.update(dt);updateSky(dt);ui.health(player.health);ui.coords.textContent=`${player.pos.x.toFixed(1)}  ${player.pos.y.toFixed(1)}  ${player.pos.z.toFixed(1)}`;renderer.render(scene,camera);if(now-lastSave>2500){saveGame();lastSave=now}}
requestAnimationFrame(loop);

ui.playBtn.onclick=()=>{ui.boot.classList.add('hidden');ui.hud.classList.remove('hidden');running=true;if(!input.mobile)renderer.domElement.requestPointerLock()};
document.addEventListener('pointerlockchange',()=>{if(input.mobile)return;const locked=document.pointerLockElement===renderer.domElement;ui.pause.classList.toggle('hidden',locked||!running);if(running&&!locked)ui.pause.onclick=()=>renderer.domElement.requestPointerLock()});
addEventListener('keydown',e=>{if(/^Digit[1-9]$/.test(e.code))ui.select(Number(e.code.slice(5))-1)});addEventListener('wheel',e=>{const n=ui.hotbarIds.length;if(!n)return;ui.select((ui.selected+(e.deltaY>0?1:-1)+n)%n)},{passive:true});
mods.onChange(()=>{world.rebuildAll();ui.toast('Mod settings updated')});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.75))});
addEventListener('beforeunload',saveGame);document.addEventListener('visibilitychange',()=>{if(document.hidden)saveGame()});
